openapi: 3.1.0
info:
  title: DTOs
  version: '1'

paths:

  /foo:
    get:
      parameters:
        - name: fooBar
          description: query parameter object
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Foo'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Bar'
        required: true
      responses:
        '200':
          description: plain text response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FooBar'

components:
  schemas:

    Foo:
      type: object
      required:
        - foo
      properties:
        foo:
          type: string
          pattern: .*\.\\
        bar:
          type: integer
          format: int64
          minimum: 1
          maximum: 12

    Bar:
      type: object
      properties:
        bar:
          type: string
          maxLength: 10

    FooBar:
      type: object
      properties:
        foobar:
          type: string
          minLength: 1
