openapi: 3.1.0
info:
  title: DTOs
  version: '1'

paths:

  /foo:
    get:
      parameters:
        - name: fooBar
          description: query parameter object
          in: query
          schema:
            $ref: '#/components/schemas/FooBar'
      responses:
        '200':
          description: plain text response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FooBar'

components:
  schemas:

    FooBar:
      type: object
      properties:
        foo:
          type: string
        bar:
          type: integer
          format: int64
