openapi: 3.1.0
info:
  title: DTOs
  version: '1'

paths:

  /foo:
    get:
      parameters:
        - name: fooBar
          description: query parameter object
          in: query
          schema:
            $ref: '#/components/schemas/Foo'
      responses:
        '200':
          description: plain text response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bar'

components:
  schemas:

    Foo:
      type: object
      properties:
        foo:
          type: string
        bar:
          type: integer
          format: int64

    # a schema with allOf creates single flattened DTO
    Bar:
      type: object
      allOf:
        - type: object
          properties:
            foo1:
              type: string
        - type: object
          properties:
            foo2:
              type: string
      properties:
        bar:
          type: string
