openapi: 3.1.0
info:
  title: type mappings
  version: '1'

paths:
  /foo:
    post:
      parameters:
        - in: query
          name: date
          schema:
            type: string:date-time

      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Foo'
        required: true

      responses:
        '200':
          description: the Bar
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bar'

components:
  schemas:

    Foo:
      type: object
      properties:
        foo:
          type: string
          format: uuid

    Bar:
      type: object
      properties:
        bar:
          type: string
