openapi: 3.0.2
info:
  title: array mapping
  version: 1.0.0

paths:
  /array:
    post:
      tags:
        - endpoint
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Foo'
        required: true
      responses:
        '200':
          description: created book
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bar'

components:
  schemas:

    Foo:
      type: object
      properties:
        foo:
          type: string

    Bar:
      type: object
      properties:
        bar:
          type: string
