openapi: 3.1.0
info:
  title: additional parameter mapping
  version: 1.0.0

paths:
  /parameter/add:
    get:
      tags:
        - endpoint
      responses:
        '200':
          description: simple result
          content:
            text/plain:
              schema:
                type: string
