openapi: 3.1.0
info:
  title: type mappings
  version: 1.0.0

paths:
  /foo:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Foo'
        required: true
      responses:
        '200':
          description: created book
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bar'

components:
  schemas:

    Foo:
      type: object
      properties:
        foo:
          type: string
          format: uuid

    Bar:
      type: object
      properties:
        bar:
          type: string
