openapi: 3.1.0
info:
  title: result mapping
  version: '1'

paths:
  /response:
    get:
      responses:
        '200':
          description: simple result
          content:
            text/plain:
              schema:
                type: string
