openapi: 3.0.2
info:
  title: result mapping
  version: 1.0.0

paths:
  /response:
    get:
      tags:
        - endpoint
      responses:
        '200':
          description: simple result
          content:
            text/plain:
              schema:
                type: string
